---
title: 'RMarkdown:  In Class Assignment'
author: "MY TRAN"
date: "Data 2401"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) ## this line makes all the code show! 
  ## and these lines are comments - anything behind a '#' doesn't run!
```


Reminder: There is a "Markdown Help" page available in RStudio. 


## In-class Activity, Markdown

Below the "Your work here" section header, do the following 3 things. To turn this in, knit the RMarkdown file, and zip and submit the html.  

1. Make a subsection called "Wise words". Put your favorite quote in a block quote. Add a functioning link to a website that provides more information about that quote.

2. Make a subsection called "My semester". Make a three column table of the current courses you are taking, with separate columns for course number (put those in __bold__), course title (put those in _italics_), and instructor name.

3. Lastly, make subsection called "I recommend", and add some information about your favorite author or musician.

+ A _subsubheading_ with the name of the artist or author;    
+ An example of their writing or lyrics (formatted in a *plain code block*);   
+ A _list_ of things they have written or performed (remember to use the formatting markup for a list!).     


Note that you can click "Knit" as you go along to see what the final results are going to look like. **Once you're done, commit the changes and push the repo back to your assignment on GitHub!**
 
# My Tran's work here

## Wise words

>No one saves us but ourselves

[link quote](https://www.goodreads.com/quotes/498520-no-one-saves-us-but-ourselves-no-one-can-and#:~:text=No%20one%20can%20and%20no,ourselves%20must%20walk%20the%20path.%E2%80%9D)

## My semester

__Course number__  |  _Course title_    |   Instructor Name
:-----------------:|:------------------:|:-------------------:
  __DATA 2401__    |  _Data Science_    | Katherine Shoemaker
  __MATH 2305__    |  _Discrete Math_   |    Vien Nguyen
  __MATH 2422__    |  _Linear Algebra_  |   Edwin Tecarro

## I recommend

### TFBOYS

```
Shine a different light. Even if the night is too long
```

* Songs
  + Magic Castle
  + Youth

* Albums
  + Heart
  + The Big Dreamer


  